spring.application.name=carepilot-ai
server.port=8080
spring.mvc.async.request-timeout=120000

# Azure OpenAI - set environment variables before running
spring.ai.azure.openai.endpoint=${AZURE_OPENAI_ENDPOINT:}
spring.ai.azure.openai.api-key=${AZURE_OPENAI_API_KEY:}
spring.ai.azure.openai.chat.options.deployment-name=${AZURE_OPENAI_DEPLOYMENT_NAME:}
spring.ai.azure.openai.chat.options.temperature=0.2

# MariaDB
spring.datasource.url=${DB_URL:jdbc:mariadb://localhost:3306/vectordb}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.sql.init.mode=never


admin.auth.id=${ADMIN_ID:admin123}
admin.auth.password=${ADMIN_PASSWORD:Password@123}

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.web.resources.cache.period=0
springdoc.swagger-ui.path=/swagger-ui
